maistra/maistra-test-tool

.gitignore

This includes `vim` and `goland` (JetBrains Go IDE)

chore: ignores more IDE specific local files

---

tests/config/excludeOutboundPortsAnnotation/app-v2.yaml
tests/samples.go
tests/test_cases.go
tests/test_excludeOutboundPorts_annotation.go
tests/util/ocp_utils.go

Adding automation to MAISTRA-2134.
Instead of kubectl, I changed to use the default `oc` image.
@cfilleke  this [image](https://catalog.redhat.com/software/containers/openshift4/ose-cli/5cd9ba3f5a13467289f4d51d?container-tabs=gti) has an equivalent in `s390x` and `ppc64le`

Adding Automation for MAISTRA-2134

---

tests/samples_extend.go

We're making some incompatible changes to this filter in 2.1, so we need to reference the 2.0 version for the 2.0 tests

MAISTRA-2413 Pin version of header-append-filter

---

pkg/util/common.go

Use `t.Fatal()` instead of `t.Error()` so that tests are aborted
when encounter an error.

Fail fast in util.Inspect()

---

pkg/ossm/initContainer.go
pkg/ossm/yaml_configs.go
tests/test_cases.go

This case tests if the init container is not removed
when injecting the sidecar proxy.

OSSM-734: Add test to cover the init container case

---

testdata/examples/federation/cleanup.sh

For some reason, `oc delete project` does not wait like `oc delete namespace` does, and not even adding the --wait flag helps.

OSSM-1412 Use `oc delete ns` instead of `oc delete project`

---

pkg/ossm/sme_install.go

PR to disable T25 test case for interop testing. Reference bug - https://issues.redhat.com/browse/OSSM-1505

Disable T25 test case for interop testing

---

tests/test_cases.go

As the fix for skip test on OCP 4.11 is not yet done, creating PR to temporary disable the T25 test for interop testing

Disable T25 test case for interop testing for maistra-2.1

---

pkg/examples/nginx.go
pkg/examples/yaml_vars.go
pkg/tasks/traffic/egress/egress_gateways_tls_file_mount.go
pkg/tasks/traffic/egress/egress_gateways_tls_sds.go
pkg/tasks/traffic/egress/yaml_configs.go
pkg/tasks/traffic/egress/yaml_vars.go
pkg/tasks/traffic/ingress/yaml_configs.go
testdata/examples/x86/nginx/nginx.yaml
tests/test_cases.go

Signed-off-by: Yuanlin <yuanlin.xu@redhat.com>
This PR adds the egress gateway mtls ori tests (file mount and SDS) back when testing on an OCP cluster.
The main difference between upstream istio.io doc and our steps is applying an additional ServiceEntry for egress gateway resolving the hosts such as "my-nginx.mesh-external.svc.cluster.local" in a VirtualService route.

OSSM-2078 Fix egress gateway mtls flaky tests

---

pkg/ossm/bug_istiopods.go
pkg/util/kube.go

After testing the T35 over a ROSA cluster the test case fails because the container inside the pod fails the first readiness probe, So I include an improvement to check when the container is n of n ready
https://issues.redhat.com/browse/OSSM-3023

Improve T35 testcase to avoid errors over ROSA cluster

---

pkg/util/kube.go

Increase the BaseDelay from 1 to 10 seconds to make sure that the check is not doing very  quickly

Increase BaseDelay on CheckReady func

---

pkg/ossm/smcp_tls_ssl.go

In the test case, T27 TestSSL needs to pass to the command ./testssl/testssl.sh the flag -6 to add support to IPv6 according to the documentation: 
https://testssl.sh/#:~:text=http(s)_proxy)-,%2D6,-also%20use%20IPv6
Was tested on IPv4 OCP cluster to check compatibility:
`servicemeshcontrolplane.maistra.io/basic condition met
--- PASS: T27 (232.25s)
--- PASS: T27/Operator_test_smcp_testssl (196.18s)`

Adding support for IPv6 on testssl.sh

---

Dockerfile
pkg/examples/sleep.go
pkg/ossm/init.go
pkg/ossm/yaml_vars.go
pkg/tasks/traffic/egress/egress_gateways.go
pkg/tasks/traffic/egress/egress_tls_origination.go
pkg/util/kube.go
testdata/examples/x86/sleep/sleep.yaml
testdata/examples/x86/sleep/sleep_legacy.yaml
tests/test.env

Looking to improve the code and simplify the run of the test cases over the IPv6 cluster that uses PROXY env variables, I made some changes to the code to set some curl to the internet using -x flag and to set the proxy env variable to sleep pod.
The issue related on jira: https://issues.redhat.com/browse/OSSM-3377

Set proxy variables from oc get proxy to avoid issue on IPv6 cluster

---

pkg/ossm/operator.go

We need to increase the wait time for the smcp condition Ready to avoid Flaky test execution

Increase wait time for smcp ready in T40 execution

---

pkg/tasks/security/authorization/externalauthorization.go

Avoid smcp deleting in T37 cleanup function

avoid smcp deletion in T37

---

pkg/ossm/bug_multiple_smcp.go
tests/test_cases.go

The T36 test case is causing the next test cases to fail because all the istio resources are deleted. Meanwhile, the bahaviour is analized, this test case is deactivated to avoid failures in daily runs

Deactivate T36 test case to avoid next test cases to fail

---

pkg/util/oc/pod_commands.go

After we made some changes, we left an error in WaitCondition: namespace is named ns and a parenthesis missing

fix error in WaitCondition

---

pkg/ossm/bug_multiple_smcp.go
pkg/ossm/yaml_vars.go
tests/test_cases.go

Changes to the T36 test case:
Created the istio-system2 namespace
Deployed the Multiple SMCP on that new namespace
Deleted Istio Operator pod, it will recreate the Webhook back again.
This is already reviewed by Marko. I have updated the latest changes, but unexpectedly this PR is deleted. 
Here, is the previous PR - https://github.com/maistra/maistra-test-tool/pull/394

refactor the t36 test case

---

pkg/app/echo-v1.go
pkg/app/echo-v2.go
pkg/app/echo.go
pkg/examples/yaml_vars.go
pkg/tests/tasks/security/authorization/tcp_test.go
pkg/tests/tasks/security/authorization/yaml_configs.go
pkg/util/oc/pod_commands.go
testdata/examples/x86/tcp-echo/tcp-echo-v1.yaml
testdata/examples/x86/tcp-echo/tcp-echo-v2.yaml

This PR includes:
- Refactor T21 TestAuthorizationTCPTraffic
- Refactor tcp-echo exaple app go code and yaml manifests . They will be used in the T4 test TCP traffic shifting refactoring next.

OSSM-3721 Refactor T21 TestAuthorizationTCPTraffic

---

pkg/app/redis.go
pkg/examples/yaml_vars.go
pkg/tests/ossm/ratelimit_test.go
pkg/tests/ossm/yaml/smcp-patch-rate-limiting.yaml
pkg/util/env/env.go
pkg/util/version/version.go
pkg/util/version/version_test.go

Jira ticket: https://issues.redhat.com/browse/OSSM-3741
Refactored the test case with these changes:
- Created redis.go to install Redis application with the new framework
- Changed the unit to allow requests with the rate limit feature
- Skip the test in v2.3+ 
Executed this test against OCP 4.13 and works with the new configuration

OSSM-3741 Refactor TestRateLimiting T28

---

pkg/tests/ossm/initcontainer_test.go
pkg/tests/tasks/traffic/ingress/secure_gateways_test.go
pkg/util/oc/pod_commands.go
pkg/util/pod/pods.go

When pod didn't exist, the function returned an empty NamespacedName instead of failing. This caused some tests to fail.

Fix pod.MatchingSelector()

---

pkg/tests/tasks/security/authorization/tcp_test.go

The test recreated the mesh namespace (with no special reason), causing the next text to fail because the SMCP was missing.

Ensure TestAuthorizationTCPTraffic doesn't break other tests

---

pkg/tests/ossm/smcp_annotation_test.go
pkg/util/test/test_helper.go

This small change cuts the test duration in half (from 40s to 20s).

Run TestSMCPAnnotations subtests in parallel

---

pkg/tests/ossm/smcp_annotation_test.go

These annotations caused TestSSL to fail.

Proper clean up after TestSMCPAnnotations

---

scripts/compiletests.sh

The make check command compiled the tests and polluted the working directory with *.test files. This change prevents those files from being created.

Fix make check

---

pkg/tests/tasks/security/authentication/auth_test.go

This fixes the TestAuthPolicy, which called oc.ApplyTemplate on strings that weren't actually templates.

Clean up TestAuthPolicy

---

pkg/tests/non-dependant/bug_multiple_smcp_test.go

The test didn't wait for the operator to be ready, but only for the validatingwebhookconfiguration to appear. This doesn't suffice, as the next test will update the SMCP immediately and the webhook will fail because the operator can't yet respond to webhook requests.

Ensure TestSMCPMultiple doesn't affect the next test

---

Dockerfile
pkg/tests/ossm/setup.go
tests/test.env

IPV6 is not used and GODEBUG is no longer needed. It was fixed by https://github.com/maistra/maistra-test-tool/pull/341

Remove unused env variables

---

pkg/tests/ossm/setup.go
pkg/util/oc/oc.go
pkg/util/oc/oc_struct.go
pkg/util/oc/pod_commands.go

This ensures that the resulting SMCP spec exactly matches what each test needs. Previously, we used `oc apply`, which doesn't remove spec fields that were added by the previous test(s).

OSSM-3840 Use `oc replace` when setting up SMCP

---

pkg/util/oc/oc_struct.go
pkg/util/oc/pod_commands.go
pkg/util/retry/retry.go

- make failures easier to debug by logging the output of `oc describe` after the `oc wait` command fails
- log "Wait for condition..." instead of low-level `shell.Execute` failures

Improve oc.WaitCondition

---

pkg/util/env/env.go
scripts/runtests.sh

- split results dir into separate, per-version dirs
- store entire log output to output.log
- store logs of failed test to failed.log
- store skipped tests to skipped.log
- include "DONE" and the next line (such as "ERROR ending test run because max failures was reached") in test summary

Improve runtests

---

pkg/tests/tasks/security/certificate/cert_manager_test.go
pkg/util/check/assert/common.go
pkg/util/check/assert/output.go
pkg/util/check/common/output.go
pkg/util/check/require/common.go
pkg/util/check/require/output.go

If the foo namespace exists and already contains the `istio-ca-root-cert`, the cert-manager-istio-csr logs contain `updating ConfigMap data` instead of `creating configmap with root CA data`

Fix TestCertManager

---

.dockerignore
Dockerfile

We need an image which can be run on OCP. This is first change which is required. It contains also some minor improvements.

OSSM-3669: initial changes for interop pipeline support

---

pkg/tests/tasks/security/certificate/cert_manager_test.go

Although the test previously did delete the namespace, the cert-manager operator apparently recreated it. So, we must first terminate the operator and then delete the namespace.

Ensure the cert-manager namespace is cleaned up in TestCertManager

---

Makefile

You can now run `make test-cleanup` if you interrupt a test run and want to clean things up (the test code doesn't do this on its own if you interrupt it).

make test-cleanup

---

Jenkinsfile

Jenkinsfile is now located in https://gitlab.cee.redhat.com/istio/servicemesh-qe/jenkins-csb-declaration

OSSM-3807: removing Jenkinsfile as new version is now used

---

scripts/runtests.sh

MacOS uses bash3, so we have to use indexed instead of associative arrays.

Make runtests.sh runnable on MacOS

---

pkg/tests/tasks/security/authorization/trust_domain_test.go

For 2.1 smcp version we need to restart deployments in meshNamespace

Fix TestTrustDomainMigration

---

scripts/runtests.sh

This is needed to comply with jenkins job behavior

Make sure the token takes precedence over usr/pass when both are set

---

pkg/tests/tasks/security/certificate/external_ca_test.go

Updates TestExternalCertificate to use methods from `crypo/x509` over calls to `openssl` and file comparison. I also took the time to really understand what the test was trying to accomplish and re-wrote the test to eliminate unnecessary steps.
The test now only verifies:
1. That the certificates stored in the admin-provided `cert-chain.pem` are included in the returned certificates.
- `cert-chain.pem` contains a chain of certificates beginning with (and including) the certificate from `ca-cert.pem` and ending just before (but not including) the certificate from `root-cert.pem`. Therefore, it is redundant to check for the certificate from `ca-cert.pem` in the returned certificates.
- The certificate from `root-cert.pem` _may_ be returned by the endpoint, but it serves no purpose as the …

Update TestExternalCertificate to use x509

---

pkg/tests/tasks/traffic/circuit_breaking_test.go

Jira: https://issues.redhat.com/browse/OSSM-3871
**TestCircuitBreaking**: change the number of requests per second to adjust and avoid condition meet of failures, no will be 10 request per second to the DestinationRule defined:
```
trafficPolicy:
connectionPool:
tcp:
maxConnections: 1
http:
http1MaxPendingRequests: 1
maxRequestsPerConnection: 1
outlierDetection:
consecutiveErrors: 1
interval: 1s
baseEjectionTime: 3m
maxEjectionPercent: 100
```

OSSM-3871 Fix Flaky test: TestCircuitBreaking

---

pkg/util/oc/oc_struct.go
pkg/util/test/test_helper_setup.go

To be able to fix some flaky tests as SingleClusterFederation I made some changes to func ApplyString and ApplyFile to make retries and log as Warning every time that a apply fails
Jira for flaky test: https://issues.redhat.com/browse/OSSM-3871?filter=12407518

OSSM-3871 Improve Apply String, template and file

---

pkg/tests/non-dependant/smcp_install_test.go

By mistake when I merged some change I duplicate a subtest case in SMCPInstall

Delete tnon used test in SMCPInstall

---

pkg/tests/tasks/security/certmanager/istio_csr_test.go
pkg/tests/tasks/security/certmanager/main_test.go
pkg/tests/tasks/security/certmanager/plugin_ca_test.go
pkg/util/oc/oc.go
pkg/util/oc/oc_struct.go
pkg/util/test/test_helper_setup.go
pkg/util/version/version.go

Jira: https://issues.redhat.com/browse/OSSM-3967
Added a ocp check version to get the version and skipped in test cases that does not work with some OCP version

OSSM-3967 Fix Cert manager test cases

---

pkg/tests/tasks/security/certmanager/plugin_ca_test.go
pkg/tests/tasks/security/certmanager/yaml/cacerts/mesh.yaml

For ROSA this test case was failing because we need to set: 
```
identity:
type: ThirdParty
```

Fix TestPluginCaCert

---

pkg/tests/ossm/yaml/smcp.yaml
pkg/tests/tasks/traffic/circuit_breaking_test.go
pkg/util/oc/oc.go
pkg/util/oc/service_commands.go

The tool fortio that is used in the test, resolves hostnames to IPv4 address by default and therefore the test was failing on IPv6 cluster. As you can see on the screenshot, fortio queries DNS for A records, not A and AAAA, so requests were failing.

OSSM-3420: Fix TestCircuitBreaking in IPv6 stack

---

pkg/tests/ossm/setup.go
pkg/tests/ossm/yaml/smcp.yaml
pkg/util/oc/oc.go
pkg/util/oc/oc_struct.go

TestAuthPolicy was failing, because istiod could not properly process RequestAuthentication object due to networking issue:
```
error model Failed to refresh JWT public key from "https://raw.githubusercontent.com/istio/istio/release-1.9/security/tools/jwt/samples/jwks.json": Get "https://raw.githubusercontent.com/istio/istio/release-1.9/security/tools/jwt/samples/jwks.json": dial tcp [<ipv6_address>]:443: connect: no route to host
warn model Failed to GET from "https://raw.githubusercontent.com/istio/istio/release-1.9/security/tools/jwt/samples/jwks.json": Get "https://raw.githubusercontent.com/istio/istio/release-1.9/security/tools/jwt/samples/jwks.json": dial tcp [<ipv6_address>]:443: connect: no route to host. Retry in 1s
```
Our IPv6 cluster requires proxying egress traffic through a …

OSSM-3418: Fix TestAuthPolicy on IPv6 stack

---

images.yaml

`TestSecureGateways` uses `image istio/examples-helloworld-v1:latest` that was built 6 years ago and does not support IPv6. I replaced that image with `quay.io/jewertow/examples-helloworld-v1:latest` that is built from the recent code implementation supporting IPv6. This is a temporary change and we will have to replace this image once the community image will be available. I will open an issue in Istio repository to rebuild and push that image.

OSSM-3423: Fix TestSecureGateways on IPv6

---

pkg/tests/ossm/deploy_on_infra_test.go
pkg/tests/ossm/smcp_annotation_test.go

Jira:
TestSMCPAnnotations is flaky because the second sub-test case is getting empty annotations, made some changes:
- Improve clean up, it's flake test related but this will improve execution time
- Added a length check to fail and retry in annotation is equal to zero

OSSM-3871 TestSMCPAnnotations flaky test

---

pkg/tests/tasks/observability/custom_prometheus_test.go

Added ~~TestPrometheusExtensionProvider~~ TestCustomPrometheus to test [OSSM-3288](https://issues.redhat.com/browse/OSSM-3288).
Currently this test has a couple of issues:
- ~~We need to use a custom bookinfo-productpage container image. I currently achieve this by directly modifying `app.BookinfoTemplate` and restoring it in `Cleanup`. Other options would be:~~
- ~~deploy bookinfo manually and not leverage the `app` package.~~
- ~~add some mechanism to hook into `template.image`.~~
- There appears to be a bug affecting the uninstall of the Prometheus operator currently. In the test I effectively uninstall the operator by deleting the namespace it is contained in, but I have also tested removing it according to OpenShift documentation by first removing the Subscription and then the …

Add TestPrometheusExtensionProvider

---

pkg/tests/ossm/smoke_test.go

Enable again the sub test case delete smcp with small changes:
- Now the validation of the deletion of the smcp is not done using oc.GetAllResources because the routes for bookinfo are not deleted (more info in: https://issues.redhat.com/browse/OSSM-4064)
- To validate the deletion the test case verifies: smcp does not exist, pods does not exists, services does not exist

Enable Sub test case: delete smcp in Smoke Test

---

pkg/metallb/install.go

Updated stale reference to `ParseOCPVersion` to its replacement, `ParseVersion`.

Update `ParseOCPVersion` reference in metallb

---

pkg/tests/ossm/smoke_test.go

After the latest change, we decrease the proxy startup time limit to 3 seconds, I'm rolling back those changes because we are getting false failures in some env that are more slow than usual. We set against the limit in 10 seconds and more than that is considered as a real failure

Rollback to change of proxy startup time

---

pkg/util/oc/oc_struct.go

Testing in ROSA cluster (created using cluster bot) I saw that the response to
```
oc get proxy cluster -o jsonpath='{.status}'
```
Can be an empty string, this case was not managed so I added validation to return an empty Proxy if proxyjson is empty. This needs to be done because our customer that wants to run the tool can have this type of issue

Return empty proxy when status cluster proxy does not exist

---

pkg/tests/ossm/operator/clusterwide_mode_test.go

Jira: https://issues.redhat.com/browse/OSSM-3995
Adding a new sub-test case related to the task, where we validate that a regular user cannot add projects to the SMMR unless the user has the correct roles to do it.
Scenario:
Test: validate required privileges for SMMR
Sub-test cases:
- Case 1: user has admin role only in mesh namespace. Expectation: user can't edit SMMR with member-0 and member-1 namespaces
- Case 2: user has admin role only in mesh namespace. Expectation: user can't edit SMMR with * wildcard
- Case 3: user has admin role in mesh, member-0 and member-1 namespaces. Expectation: user can edit SMMR
- Case 4: user has admin role in member-0 and member-1 namespaces. Expectation: user can't edit SMMR
tested locally:
```
--- PASS: TestClusterWideMode (125.13s)
--- PASS: …
```

OSSM-3995 Cluster-wide new test case related privileges to update SMMR

---

pkg/tests/ossm/smcp_must_gather_test.go

Jira: https://issues.redhat.com/browse/OSSM-4223
To fix the flaky test case MustGather we change the target file in the folder role bindings of the istio-system namespace, now we are going to use mesh-user.yaml

OSSM-4223 Fix target file in must gather test case

---

pkg/tests/ossm/deploy_on_infra_test.go

Jira: https://issues.redhat.com/browse/OSSM-3837
This test case could not be executed in a test run because of some failures that made to be tainted bot worker nodes. Changes made:
- Revert to patch servicemeshoperator moved to clean upper func because was causing operator hangout because the taints are active when that sub test case finish
- Added a operator pod deletion because sometimes is not automatically moved (Opened a new jira to investigate this: https://issues.redhat.com/browse/OSSM-4260)
- Fix error on func pickWorkerNode. We were picking both worker nodes so both workers was taint and this causes failures

OSSM-3837 Fix errors on TestDeployOnInfraNodes

---

pkg/metallb/install.go
pkg/tests/tasks/observability/custom_prometheus_test.go
pkg/tests/tasks/observability/openshift_monitoring_test.go
pkg/tests/tasks/security/certmanager/main_test.go
pkg/tests/tasks/security/certmanager/yaml/cert-manager-operator.yaml
pkg/util/oc/oc.go
pkg/util/oc/oc_struct.go
pkg/util/oc/pod_commands.go

Jira: https://issues.redhat.com/browse/OSSM-4217
We have two common issues in cert-manager related tests:
- Operator cert-manager does not install and never gets ready
- Fail in setup causes panic for the test run
The first was solved updated the version of the cert-manager to the latest stable because in OCP cluster 4.13 was not running because the 1.10 version was failing in that OCP version. The second was I added a workaround because the issue is that the cert-manager takes more than 60 seconds to be installed the first time, so I added a retry until success to retry until the cert-manager is correctly installed. Additionally to this we need to verify why the Setup test helper is finishing with panic and is not accepting to change to the same behavior than test helper (This will be …

OSSM-4217 Fix issues with cert manager setup

---

pkg/metallb/install.go
pkg/tests/ossm-federation/federation_traffic_splitting_test.go
pkg/tests/ossm-federation/main_test.go

Jira: https://issues.redhat.com/browse/OSSM-4358
This PR use the changes to be done in this PR by @jewertow : https://github.com/maistra/maistra-test-tool/pull/583. This deploy MetalLB when the variable METALLB_INTERNAL_IP_ENABLED is true. 
I made a few changes to be able to use both single cluster federation in Multicluster scenario also, so those test case are now called: TestFederationDifferentCerts and TestFederation, and they are executed as singlecluster when only 1 kubeconfig file is given and as multicluster when two kubeconf are given

OSSM-4358 Change SingleCluster federation test to work with multicluster also

---

pkg/tests/tasks/observability/custom_prometheus_test.go

Jira: https://issues.redhat.com/browse/OSSM-4357
The case is not supported on OCP versions less than 4.10 because Prometheus Operator it's not available from red hat catalog

OSSM-4357 skip custom prometheus test case on version older than 4.11

---

pkg/tests/tasks/traffic/ingress/gatewayapi_test.go

Gateway-Controller Profile it's not available in versions of SMCP less than 2.4. So I added a skip for that case

skip Deploy the Gateway-Controller Profile for version les than 2.4

---

pkg/tests/tasks/security/certmanager/istio_csr_test.go
pkg/tests/tasks/security/certmanager/main_test.go
pkg/tests/tasks/security/certmanager/plugin_ca_test.go

Skip cert-manager test cases when OCP_ARCH is equal to z or p

skip certmanager for IBM Z&P

---

pkg/certmanageroperator/install.go
pkg/tests/tasks/observability/custom_prometheus_test.go
pkg/tests/tasks/observability/openshift_monitoring_test.go
pkg/tests/tasks/traffic/ingress/gatewayapi_test.go
pkg/util/oc/oc.go
pkg/util/oc/pod_commands.go

Jira: https://issues.redhat.com/browse/OSSM-4309
To continue improving the cert-manager test case and avoid flaky on this test I did some changes:
- Revert changes on WaitCondition, the func it's available again
- Create the func WaitForPhase to use in cert-manager test case to wait until csv is Succeed
- WaitFor is now a common func and it's used by WaitCondition and WaitForPhase
- Added a retry and a certManagerOperatorExists before to verify the phase because take around 10 seconds after the creation of the operator to be displayed the csv
Now in the cert-manager setup we will see the entire process of the creation and verification of the operator installation:
```
install.go:62: STEP 2: Install cert-manager-operator
install.go:67:    Waiting for cert-manager-operator to succeed …
```

OSSM-4309 Revert changes to WaitCondition, create WaitForPhase and avoid flaky for not created csv

---

pkg/tests/tasks/security/certmanager/istio_csr_test.go
pkg/tests/tasks/security/certmanager/plugin_ca_test.go

After executing the full run I need to move the uninstall func for cert-manager to the TestPluginCaCert to avoid uninstalling before to execute all the test cases related to cert-manager

Move uninstall from certmanager test

---

pkg/tests/tasks/observability/custom_prometheus_test.go

Jira: https://issues.redhat.com/browse/OSSM-4195
Adding print resp.Status when failure to get in the log more information about what was the failure in the request

OSSM-4195 adding more information to step in failure

---

pkg/tests/ossm/prometheus_scoped_scraping_test.go
pkg/util/oc/pod_commands.go

Jira: https://issues.redhat.com/browse/OSSM-4451
Made these changes:
- Skip test case in versions less than 2.4
- Increase the retry in checkConfigurationReloadingTriggered
- Round up in LogsSince, we can have the case where are rounding down and that can make the test flaky.

OSSM-4451 Skip TestOperatorCanUpdatePrometheusConfigMap changes and avoid flakiness

---

pkg/tests/tasks/security/authorization/tcp_test.go

Jira: https://issues.redhat.com/browse/OSSM-4474
The TCP pod is giving a flaky result when the connection is tested against the 9002 port, to avoid this I deleted the validations against the 9002 port and change the order of the sub-test cases to have the same validation but without using the 9002 port as reference. With this change we will have the same validations but without rely on having the 9002 as reference

OSSM-4474 TestAuthorizationTCPTraffic fix flaky

---

pkg/tests/ossm/ior_test.go

Jira: https://issues.redhat.com/browse/OSSM-4472
it's failing in 2.3 and less because of the non-deletion of the simple gateway route created before, so I fix the cleanup func on subtest case check the basic capabilities of IOR and now is working in 2.3 and less. Tested in both 2.3 and 2.4 version and it's working
```
--- PASS: TestIOR (258.54s)
--- SKIP: TestIOR/check_IOR_off_by_default_v2.5 (0.00s)
--- PASS: TestIOR/check_IOR_basic_functionalities (2.58s)
--- PASS: TestIOR/check_routes_aren't_deleted_during_v2.3_to_v2.4_upgrade (115.86s)
--- PASS: TestIOR/check_IOR_does_not_delete_routes_after_deleting_Istio_pod (91.50s)
```
```
--- PASS: TestIOR (124.20s)
--- SKIP: TestIOR/check_IOR_off_by_default_v2.5 (0.00s)
--- PASS: TestIOR/check_IOR_basic_functionalities (2.46s)
--- SKIP: …
```

OSSM-4472 Fix ior test case in versions less than 2.4

---

pkg/tests/tasks/security/certmanager/istio_csr_test.go
pkg/tests/tasks/security/certmanager/plugin_ca_test.go
pkg/util/oc/oc_struct.go

Jira: https://issues.redhat.com/browse/OSSM-4601
We have some flaky result in interop pipeline, certmanager take a lot of time to come up so we removed certmanager related test cases from interop run and TestTLSOriginationSDS was flaky because in some point the api it's not ready when we delete the certificate after install ngnix, so to mitigate this failure I added a retry in the delete cert command to retry if we got failures in the process

OSSM-4601 Delete test from interop run and add retry to delete cert

---

pkg/tests/tasks/observability/custom_prometheus_test.go
pkg/tests/tasks/observability/federated_openshift_monitoring_test.go
pkg/tests/tasks/observability/main_test.go
pkg/tests/tasks/observability/openshift_monitoring_test.go
pkg/tests/tasks/observability/yaml/federated-monitor.yaml
pkg/tests/tasks/observability/yaml/federated-monitoring-mesh.tmpl.yaml
pkg/util/prometheus/prometheus.go
pkg/util/prometheus/prometheus_struct.go

Added `TestFederatedOpenShiftMonitoring` in `pkg.tests.tasks.observability` to test support for federating metrics from Service Mesh to OpenShift's monitoring stack.
- Added `TestFederatedOpenShiftMonitoring` (in `federated_openshift_monitoring_test.go`).
- Moved a couple monitoring constants from `openshift_monitoring_test.go` to `main.go` as they are used in `TestFederatedOpenShiftMonitoring` as well.
- Added variable `DefaultThanos`, a new default `Prometheus` instance configured for OpenShift monitoring's Thanos.
- Added function `ThanosQuery` to support easy queries to OpenShift monitoring's Thanos instance (proxy for `DefaultThanos.Query`).
- Renamed variable `CustomPrometheus` to `DefaultCustomPrometheus` to be in line with `DefaultThanos` and `DefaultPrometheus`.
- Added function …

Add TestFederatedOpenShiftMonitoring

---

README.md
pkg/tests/tasks/observability/federated_openshift_monitoring_test.go
pkg/tests/tasks/observability/openshift_monitoring_test.go
pkg/tests/tasks/security/certmanager/istio_csr_test.go
pkg/tests/tasks/security/certmanager/plugin_ca_test.go
pkg/util/env/env.go
scripts/runtests.sh
templates/smcp-templates/v2.5/cr_2.5_default_template.yaml

Jira: https://issues.redhat.com/browse/OSSM-4658
Update all the files to work with 2.5 Operator version. Set new default version to 2.5 SMCP and 2.5.x operator version

OSSM-4658 Update files to be able to work with 2.5.x operator version by default

---

README.md
pkg/util/env/env.go
pkg/util/test/subtest.go
pkg/util/test/test.go

Jira: https://issues.redhat.com/browse/OSSM-4701
Adding the retrieve of the environmental variable MUST_GATHER to enable or disable must gather collection after test case failures

OSSM-4701 Adding the capability to enable or disable must gather after test case failure

---

pkg/tests/tasks/security/certificate/alpn_filter_non_istio_test.go

Added `TestAlpnFilterDisabledForNonIstioMtls` to verify that ALPN filtering is disabled for non-Istio traffic. See Istio issue [#40680](https://github.com/istio/istio/issues/40680).

OSSM-4056: Add TestAlpnFilterDisabledForNonIstioMtls

---

images.yaml

updating the X86 bookinfo version is causing some errors for the traffic generator.
After this fix, the traffic generator ran successfully.

MTT: fix_BI_failures

---

pkg/tests/ossm/smoke_test.go

Tested through local and Jenkins with the 2.5 build. It run successfully.

OSSM-5388: Fix 2.5 smoke test

---

pkg/tests/tasks/extensions/threescale_wasm_plugin_test.go

Web Assembly IBM P/Z is not supported for the IBM P/Z platform.
Error from server (NotFound): namespaces "3scale" not found
reformatted the code to skip the test case properly.

OSSM-5596:Skip Web Assembly IBM P/Z

---

pkg/tests/ossm-federation/federation_common.go
pkg/tests/ossm-federation/federation_failover_test.go
pkg/tests/ossm-federation/federation_traffic_splitting_test.go
pkg/tests/ossm-federation/testdata/failover/east-mesh/smcp.yaml
pkg/tests/ossm-federation/testdata/failover/west-mesh/smcp.yaml
pkg/tests/ossm-federation/testdata/traffic-splitting/east-mesh/smcp.yaml
pkg/tests/ossm-federation/testdata/traffic-splitting/west-mesh/smcp.yaml
pkg/tests/ossm-federation/testdata/traffic-splitting/west-mesh/smcp_custom_cert.yaml

ref: https://issues.redhat.com/browse/OSSM-5611
info: https://redhat-internal.slack.com/archives/C04KW747ZLK/p1704453981200879

[OSSM-5611] Workaround for cleaning instability on OCP in PSI

---

images.yaml
pkg/tests/tasks/traffic/common.go
pkg/tests/tasks/traffic/fault_injection_test.go
pkg/tests/tasks/traffic/request_routing_test.go
pkg/tests/tasks/traffic/request_timeouts_test.go
pkg/tests/tasks/traffic/traffic_shifting_test.go
testdata/resources/html/productpage-normal-user-v1.html
testdata/resources/html/productpage-normal-user-v2.html
testdata/resources/html/productpage-normal-user-v3.html
testdata/resources/html/productpage-test-user-v2-rating-unavailable.html
testdata/resources/html/productpage-test-user-v2.html

I found this away
Steps:
1. getting the review pod name and assigned to the variable
2. adding the variable to the existing the HTML file
3. creating the new updated file in the same folder
4. compared with the new file.

OSSM-5382: Fixing the BI test case

---

pkg/tests/ossm/initcontainer_test.go

https://hub.docker.com/r/curlimages/curl/tags
s390x platform is not available in the latest tag.
Created the curl issue: https://github.com/curl/curl-container/issues/46#issuecomment-1869611737 for the IBM-Z platform, it affects one test case in the Maistra-test-tool. 
once it is resolve, we can update back to latest. 
This test case fails in the IBM-Z platform.

 OSSM-5819: Update the curl image tag

---

pkg/certmanageroperator/install.go

The cert-Manager operator version is updated to 1.13.0

update cert manager version

---

pkg/tests/tasks/security/authentication/auth_test.go
pkg/tests/tasks/security/authorization/tcp_test.go
pkg/tests/tasks/security/authorization/trust_domain_test.go
pkg/tests/tasks/traffic/ingress/secure_gateways_test.go
pkg/util/oc/oc_struct.go

I have changed logic in one test: [code](https://github.com/maistra/maistra-test-tool/compare/main...unsortedhashsets:maistra-test-tool:OSSM-3903?expand=1#diff-cbdd641c277eec8e5fd7bd89cf0bc42a0485ec443082b708e1cb1e9072d5e325R111)
From my point of view if we just want to check that the connection failed we can use the existing function `assertConnectionFailure` but for expanded test the reason can be only to check the zeroes curl placeholder in response :thinking: 
Issue: https://issues.redhat.com/browse/OSSM-3903

[OSSM-3903] Improve log step and log in current test cases

---

pkg/tests/ossm/ior_test.go

`oc -n istio-system get smcp/basic -o jsonpath='{.status.appliedValues.istio.gateways.istio-ingressgateway.ior_enabled}' = true`
In the 2.5, it is set to be the "true"

OSSM-5446: fix IOR test case for 2.5 & ARM

---

pkg/tests/tasks/observability/openshift_monitoring_test.go
pkg/util/oc/oc.go
pkg/util/oc/pod_commands.go

The test is waiting till kiali CR is reconciled by Istio, but is not waiting till a new Kiali pod is running (and the old one is deleted).
Therefore, it fetches the Kiali token from the older Kiali pod and that is why a query to the thanos fails on `Unauthorized`

Fix invalid token in openshift_monitoring_test

---

pkg/tests/tasks/traffic/ingress/secure_gateways_test.go
pkg/util/check/assert/http_response.go
pkg/util/check/common/http_response.go

Curl Against regular cluster, it fails with msg `certificate required`
```
* processing: https://httpbin.example.com:/status/418
* Added httpbin.example.com:443:10.0.191.52 to DNS cache
* Hostname httpbin.example.com was found in DNS cache
*   Trying 10.0.191.52:443...
* Connected to httpbin.example.com (10.0.191.52) port 443
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: ./sampleCerts/httpbin.example.com/example.com.crt
*  CApath: none
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), …
```

Fix tls error message check on FIPS cluster

---

pkg/util/check/common/http_response.go

I forgot to add `return` if a request error is null during changing `CheckRequestFailureMessagesAny` function here https://github.com/maistra/maistra-test-tool/pull/669

Fix nil when request fails without response body

---

images.yaml

Updated `ext-authz` images to contain this fix  https://github.com/maistra/istio/pull/950 
`quay.io/maistra/ext-authz:0.0-ibm-p` was rebuilt under the same tag so no update is needed

Update ext-authz images

---

README.md
images.yaml
pkg/tests/ossm/testssl_test.go
pkg/util/test/test.go

arm64 value is present in the Kiali integration and Kiali cypress. 
In the Maistra-test-tool, if we update the value from the arm to arm64. it works with the downstream run.

updating the arm to arm64

---

images.yaml

TestIngressGateways
TestSecureGateways
TestOperatorCanUpdatePrometheusConfigMap
All these test cases are failing with the old image. 
tested locally with the IBM-Z cluster, all test cases are passed as expected.

[OSSM-6574]: MTT-update the httpbin image for IBM-Z

---

pkg/tests/tasks/observability/custom_prometheus_test.go

TestCustomPrometheus this test case is failing, the test case is running before the operator is installed.
added the step to check the pod, once the Prometheus operator pod is ready then it would be easy to verify the next steps.

[OSSM-6582]  MTT: Fixing the flaky for the Prometheus pod

---

pkg/tests/ossm/prometheus_scoped_scraping_test.go
pkg/tests/ossm/ratelimit_test.go
pkg/tests/ossm/smcp_must_gather_test.go
pkg/tests/ossm/smm_test.go
pkg/tests/ossm/smoke_test.go
pkg/tests/tasks/extensions/threescale_wasm_plugin_test.go
pkg/tests/tasks/traffic/circuit_breaking_test.go
pkg/tests/tasks/traffic/ingress/gatewayapi_test.go

Based on discussion: https://github.com/maistra/maistra-test-tool/pull/687
1. In case of `test` pkg redundant import (general and dot) hold dot import.
Redundancy example:
```
"github.com/maistra/maistra-test-tool/pkg/util/test"
. "github.com/maistra/maistra-test-tool/pkg/util/test"
```
2. Replace `namespaces "github.com/maistra/maistra-test-tool/pkg/util/ns"` import to just `"github.com/maistra/maistra-test-tool/pkg/util/ns"`
3. Clean one accidentally added commentary

[OSSM-6572] MTT: Delete redunduncies in test pkg import, cleanup

---

README.md
pkg/tests/tasks/extensions/threescale_wasm_plugin_test.go
pkg/tests/tasks/observability/federated_openshift_monitoring_test.go
pkg/tests/tasks/observability/openshift_monitoring_test.go
pkg/tests/tasks/security/certmanager/istio_csr_test.go
pkg/tests/tasks/security/certmanager/plugin_ca_test.go
pkg/tests/tasks/traffic/ingress/gatewayapi_test.go
pkg/util/env/env.go
pkg/util/gatewayapi/gatewayapi.go
pkg/util/version/smcp_version.go
scripts/runtests.sh
templates/smcp-templates/v2.6/cr_2.6_default_template.yaml

- Updated files to be able to work with 2.6.x version
- Bump GatewayAPI to v1.0.0 for SMCP 2.6

Update files to be able to work with 2.6.x version

---

pkg/tests/ossm/deploy_on_infra_test.go
pkg/tests/ossm/operator/clusterwide_mode_test.go
pkg/tests/ossm/route_prevent_additional_ingress_test.go
pkg/tests/ossm/smoke_test.go
pkg/tests/ossm/yaml/smcp.yaml
templates/smcp-templates/v2.5/cr_2.5_default_template.yaml
templates/smcp-templates/v2.6/cr_2.6_default_template.yaml

* Adapted tests to not check Jaeger on SMCP v2.6

[OSSM-6732] Removed explicitly specified tracing type from SMCP files

---

pkg/tests/ossm/smoke_test.go
pkg/util/cni/cni.go
pkg/util/compare.go

Integrated CNI prune/preserve checks in smoke upgrade/delete tests
**TEST_CASE=TestSmoke**
**Upgrade**
```
=== RUN   TestSmoke/upgrade_v2.3_to_v2.4
...
smoke_test.go:88: STEP 14: Check that previous version CNI resources were pruned and needed resources were preserved
smoke_test.go:259:    SUCCESS: Resource ClusterRole/istio-cni was pruned
smoke_test.go:250:    SUCCESS: Resource ClusterRole/ossm-cni was preserved
smoke_test.go:259:    SUCCESS: Resource ClusterRoleBinding/istio-cni was pruned
smoke_test.go:250:    SUCCESS: Resource ClusterRoleBinding/ossm-cni was preserved
smoke_test.go:259:    SUCCESS: Resource ConfigMap/istio-cni-config-v2-3 was pruned
smoke_test.go:250:    SUCCESS: Resource ConfigMap/ossm-cni-config-v2-4 was preserved
smoke_test.go:259:    SUCCESS: Resource …
```

[OSSM-6739] Add test case for CNI resources prune

---

pkg/tests/ossm/smm_test.go
pkg/tests/ossm/smoke_test.go
pkg/util/env/env.go
pkg/util/version/operator_version.go
scripts/runtests.sh

* Use Operator version env to determine against which operator the tests are running
Right now, the SMCP version is used for Operator version ( which is not the same )

[OSSM-6761] Use the correct Operator version (not SMCP version)

---

Dockerfile

fix for:
```
oc: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by oc)
oc: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by oc)
oc: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by oc)
```
Due to a new oc binary which needs rhel9 (there is also rhel8 variant)

[OSSM-6759] Bump ubi version in test container

---

pkg/tests/ossm/smoke_test.go
pkg/util/oc/oc.go
pkg/util/oc/oc_struct.go

Added check of Jaeger's not-existence and SMCP tracing settings for smcp 2.6+
```
smoke_test.go:154: STEP 8: Verify Jaeger and SMCP tracing settings
smoke_test.go:155:    Related issue: https://issues.redhat.com/browse/OSSM-6391
smoke_test.go:157:    Verify SMCP tracing settings
smoke_test.go:158:    SUCCESS: smcp .status.appliedValues.istio.tracing.enabled is false
smoke_test.go:167:    SUCCESS: smcp .status.appliedValues.istio.tracing.provider is none
smoke_test.go:177:    Verify that Jaeger resources (Route, Deployment, and Pod) were not created
smoke_test.go:178:    SUCCESS: Jaeger resources (pod, deployment, route) were not found
```
Extended oc.GetJson function with checks 
Related:
- https://issues.redhat.com/browse/OSSM-6737
- https://issues.redhat.com/browse/OSSM-6391
- …

[OSSM-6737] Verify that Jaeger is not created by default

---

pkg/tests/ossm/operator/clusterwide_mode_test.go
pkg/tests/tasks/traffic/ingress/gatewayapi_test.go
pkg/util/gatewayapi/gatewayapi.go

1. Added to TestClusterWideMode gateway API default state test (ClusterWide)
2. Added to TestGatewayApi gateway API default state test  (MultiTenant)
3. Added to TestClusterWideMode testcase Deploy_the_Kubernetes_Gateway_API from TestGatewayApi to test not only  on MultiTenant but also on ClusterWide
**SMCP_VERSION=2.5 TEST_CASE=TestClusterWideMode:**
```
=== RUN   TestClusterWideMode/check_Gateway_API_settings
clusterwide_mode_test.go:67: Check Gateway API is disabled by default
clusterwide_mode_test.go:69: Related issue: https://issues.redhat.com/browse/OSSM-6693
clusterwide_mode_test.go:71:    
clusterwide_mode_test.go:71: STEP 1: Check istiod deployment environment variables
clusterwide_mode_test.go:88:    Env PILOT_ENABLE_GATEWAY_API is set to false
clusterwide_mode_test.go:88: …
```

[OSSM-6738] MTT:  GatewayAPI is enabled by default in ClusterWide mode

---

pkg/certmanageroperator/install.go
pkg/util/operator/operators.go

Right now, we need to update certmanageroperator version every time it is updated. 
However, we are using `startingCSV:` in the subscription so we don't need to know what is the latest version, the olm downloads the latest one. 
So we can find it out dynamically and there is no need to update the certmanageroperatorversion anymore.

Update certmanageroperator to get version dynamicly

---

pkg/certmanageroperator/install.go

getCsvName can returns more names when it is running during upgrading the version from minVersion specified in the subscription to the latest released version. New way is more simplest

Hotfix for installing certmanageroperator

---

pkg/tests/ossm/smcp_must_gather_test.go
pkg/util/env/env.go

1. Use must gather 2.5 for ossm 2.5 (use in general must gather based on operator version)
2. Check new webhooks for 2.6
```
smcp_must_gather_test.go:112: STEP 3: Verify cluster-scoped-resources files exist in cluster-scoped-resources folder
smcp_must_gather_test.go:182:    SUCCESS: /tmp/must-gather-1670015299/**/cluster-scoped-resources/rbac.authorization.k8s.io/clusterrolebindings/istiod-internal-basic-istio-system.yaml exists
smcp_must_gather_test.go:182:    SUCCESS: /tmp/must-gather-1670015299/**/cluster-scoped-resources/admissionregistration.k8s.io/mutatingwebhookconfigurations/istiod-basic-istio-system.yaml exists
smcp_must_gather_test.go:182:    SUCCESS: /tmp/must-gather-1670015299/**/cluster-scoped-resources/admissionregistration.k8s.io/validatingwebhookconfigurations/istio-validat …
```

OSSM-6817: Update TestMustGather with new must-gather container

---

pkg/util/env/env.go

Update 2.6.0 must-gather container source from **quay** to latest build in **registry-proxy.engineering.redhat**
*Still needed to update after release
Related:
1. https://issues.redhat.com/browse/OSSM-6817
3. https://github.com/maistra/maistra-test-tool/pull/708
4. https://github.com/maistra/istio-operator/commit/a33d372e098dc22319da45f7da4002cdba7252ee
5. https://github.com/maistra/istio-must-gather/pull/29
6. https://github.com/maistra/maistra-test-tool/pull/709
7. Jenkins mtt run 2264 :green_circle:

OSSM-6817: Update 2.6.0 must-gather container source

---

pkg/tests/tasks/traffic/traffic_shifting_test.go

Separate error messages when the product page is not fully loaded ( for issues such ashttps://issues.redhat.com/browse/OSSM-6809 ) since `Response did not match any expected value and also didn't match any standard bookinfo productpage responses` is too general

Add new error message to notify that connection between product-details doesn't work

---

images.yaml
pkg/tests/ossm/testssl_test.go

Test passed with all SMCP (2.6, 2.5, 2.4) and multiarch image works on:

[OSSM-6824] Update testssl image to use openssl3

---

pkg/app/minio.go

To be able to run on IPv6 cluster which has cluster-wide proxy ( on the separate VM )

[OSSM-6858] Use Route for minio instead of incluster hostname

---

pkg/certmanageroperator/install.go
pkg/tests/tasks/security/certmanager/istio_csr_test.go
pkg/tests/tasks/security/certmanager/plugin_ca_test.go
pkg/tests/tasks/security/certmanager/yaml/istio-csr/istio-csr.yaml

Related:
- Cert-Manager test case failing for IBM Z ([OSSM-6930](https://issues.redhat.com/browse/OSSM-6930))
**TestIstioCsr**:
- Jenkins mtt run 2492  (P): :green_circle: 
- Jenkins mtt run 2494 (Z): :green_circle: 
- Jenkins mtt run 2490 (x86): :green_circle: (just to check that nothing is broken)
**TestPluginCaCert**:
- Jenkins mtt run 2502  (P): :green_circle: 
- Jenkins mtt run 2495  (Z): :green_circle: 
- Jenkins mtt run 2497  (x86): :green_circle:  (just to check that nothing is broken)
~~As it was it is still flaky need to open issue on that flakiness ...~~
Hope I was able to reduce flakiness a bit...

OSSM-6930: Resolve certmanager conflict for IBM Z&P

---

pkg/tests/ossm/smcp_logging_test.go

Close-loop
Related:
- [OSSM-7992](https://issues.redhat.com/browse/OSSM-7992)
- [OSSM-6331](https://issues.redhat.com/browse/OSSM-6331)
- [mtt-2531](https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/maistra/job/maistra-test-tool/2531/console)
2.5.1 operator fail example:
```
=== RUN   TestLogging
smcp_logging_test.go:29: This test verifies allowed logging levels for the control plane
smcp_logging_test.go:30: See https://issues.redhat.com/browse/OSSM-6331
smcp_logging_test.go:32:    
smcp_logging_test.go:32: STEP 1: Deploy control plane
smcp_logging_test.go:33:    
smcp_logging_test.go:33: STEP 2: Apply default SMCP and SMMR manifests
smcp_logging_test.go:33:    Wait for condition condition=Ready on smcp istio-system/basic...
smcp_logging_test.go:33:    FAILURE: …
```

OSSM-7992: Add test SMCP log levels

---

pkg/tests/ossm/ior_test.go

When Gateway API is installed in the cluster, `oc label gateway` use `gateways.gateway.networking.k8s.io` instead of `gateway.networking.istio.io` 
Due to that, you can see the following error in the `Check_argocd.argoproj.io_labels_from_Gateways_to_Routes_except_argocd.argoproj.io` test
```
ior_test.go:288: STEP 3: Add labels argocd.argoproj.io/instance and argocd.argoproj.io/secret-type=cluster to the existing Gateway
ior_test.go:289:    FATAL: Command failed: oc -n istio-system label gateway gw argocd.argoproj.io/instance=app argocd.argoproj.io/secret-type=cluster
Error from server (NotFound): gateways.gateway.networking.k8s.io "gw" not found
```

Fix gateway issue in ior test

---

pkg/tests/ossm/discovery_selectors_test.go

When the SMCP with cluster-wide mode is running and the next test applies a new SMCP without any mode specified (and with smcp 2.4), there will be an error in oc apply (regression, introduced by changing oc replay to oc apply , since oc apply does a merge while oc replace does delete+create ):
```
Error from server (BadRequest): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"maistra.io/v2\",\"kind\":\"ServiceMeshControlPlane\",\"metadata\":{\"annotations\":{},\"name\":\"basic\",\"namespace\":\"istio-system\"},\"spec\":{\"addons\":{\"grafana\":{\"enabled\":true},\"kiali\":{\"enabled\":true},\"prometheus\":{\"enabled\":true}},\"policy\":{\"type\":\"Istiod\"},\"proxy\":{\"accessLogging\":{\"file\":{\"name\":\"/dev/s …
```

Add namespace cleanup after clusterwide test

---

pkg/app/sleep.go
pkg/tests/ossm/privileged_pods_test.go
pkg/util/version/operator_version.go

Witch SMCP 2.4 and operator 2.6.2 
```
privileged_pods_test.go:71: STEP 3: Verify that GID was incremented by 1
privileged_pods_test.go:72:    SUCCESS: GID was incremented
privileged_pods_test.go:79:    
privileged_pods_test.go:79: STEP 4: Verify that a request from sleep to httpbin returns 200
sleep.go:134:    SUCCESS: Got expected "200"
```
Witch SMCP 2.4 and operator 2.6.0 (will be skipped to not affect interop testing)
```
privileged_pods_test.go:69: STEP 3: Verify that GID was incremented by 1
privileged_pods_test.go:70:    FAILURE: GID was not incremented; expected to find the string 'uid=1002(1002) gid=1002 groups=1002' in the output, but it wasn't found; full output:
uid=1002(1002) gid=1001 groups=1001
privileged_pods_test.go:77:    
privileged_pods_test.go:77: STEP 4: Verify that …
```

OSSM-8002: test with privileged pods with explicitly set secuityContext

---

pkg/prometheusoperator/install.go
pkg/prometheusoperator/yaml/custom-prometheus-operator.yaml
pkg/prometheusoperator/yaml/prometheus-instance.yaml
pkg/tests/tasks/observability/custom_prometheus_test.go
pkg/util/prometheus/prometheus_struct.go

- Changed custom prometheus to comunity one ( since the RH one is not available anymore, see the jira ticket )
- Refactored installing of custom prometheus to use the same way as Tempo or certmanager
`TestCustomPrometheus` test passed: https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/maistra/job/maistra-test-tool/2759/

[OSSM-8128] Use comunity prometheus operator

---

pkg/app/httpbin.go
pkg/tests/tasks/injection/native_sidecars_test.go
pkg/tests/tasks/injection/tproxy_test.go

- The httpbin app contains `tproxy` boolean, however, the value of that boolean is not propagated into the application deployment. ( so even the `HttpbinTproxy` app is used ( which sets `tproxy:true` ) , the application deployment doesn't contain `sidecar.istio.io/interceptionMode: TPROXY` label)
-  Changed apps in native sidecars test from TProxy to normal variant

[OSSM-8141] Fix missing Tproxy label in httpbin deployment (when TProxy=true) +  changed apps in native sidecars test from TProxy to normal variant 

---

pkg/tests/tasks/observability/custom_prometheus_test.go

I forgot to update the clean method in my previous custom prometheus changes PR https://github.com/maistra/maistra-test-tool/pull/739 
This causes instability in the following observability tests so the tests are failing and work only on rerun.

[OSSM-8154] Hotfix for cleaning custom prometheus operator

---

pkg/tests/tasks/observability/openshift_monitoring_test.go
pkg/tests/tasks/observability/yaml/kiali-user-workload-monitoring.tmpl.yaml
pkg/util/env/env.go

* Added Kiali version to the Kiali CR to not install the same version as the operator version ( since now, it is 1.89 operator version )
* Added waiting for Prometheus target to be ready before requesting the mesh app.
Passed on all SMCP versions: https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/maistra/job/maistra-test-tool/2769/

[OSSM-8136] Add Kiali version into kiali cr + improve stability of TestOpenShiftMonitoring test

---

pkg/tests/tasks/observability/custom_prometheus_test.go
pkg/tests/tasks/observability/federated_openshift_monitoring_test.go
pkg/util/prometheus/prometheus.go
pkg/util/prometheus/prometheus_struct.go

As in this PR https://github.com/maistra/maistra-test-tool/pull/740 , the waiting for the istio targets to appear in prometheus were added into custom Prometheus and federated openshift monitoring tests
Tests passed with all SMCP versions
TestFederatedOpenShiftMonitoring: https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/maistra/job/maistra-test-tool/2774/ 
TestCustomPrometheus: https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/maistra/job/maistra-test-tool/2775/

Add waiting for prometheus target in custom prometheus and federated openshift monitoring tests

---

pkg/tests/ossm/privileged_pods_test.go

error from the latest builds:
```
privileged_pods_test.go:84:    FAILURE: UID, GID and Groups were not changed; expected to find the string 'uid=1002(1002) gid=1002 groups=1002' in the output, but it wasn't found; full output:
uid=1002(1002) gid=1002(1002) groups=1002(1002)
```
Probably the output of `id` command was changed after the proxy base image upgrade from `uid=1002(1002) gid=1002 groups=1002` to `uid=1002(1002) gid=1002(1002) groups=1002(1002)`
https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/maistra/job/maistra-test-tool/2831/

Fix expected output for uid/uid after base image change

---

pkg/tests/ossm/privileged_pods_test.go
pkg/tests/ossm/smcp_logging_test.go

For `privileged_pods` to accept both `id outputs:
```
uid=1002(1002) gid=1002(1002) groups=1002(1002)
```
```
uid=1002(1002) gid=1002 groups=1002
```
https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/maistra/job/maistra-test-tool/2867/
For `smcp_logging`, sometimes the error message were sorted differently:
```
Error from server (BadRequest): admission webhook "smcp.validation.maistra.io" denied the request: [istiod doesn't support 'trace' log level, istiod doesn't support 'critical' log level]
```
```
Error from server (BadRequest): admission webhook "smcp.validation.maistra.io" denied the request: [istiod doesn't support 'critical' log level, istiod doesn't support 'trace' log level]
```
https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/m …

Improve string comparison for privileged_pods and smcp_logging tests

---

pkg/tests/ossm/bug_istiopods_test.go

Related (test covers two issues):
- [OSSM-2169](https://issues.redhat.com/browse/OSSM-2169)
- [OSSM-2420](https://issues.redhat.com/browse/OSSM-2420)
- MTT run with GA operator: [3061](https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/maistra/job/maistra-test-tool/3061/)

OSSM-8252: Add pod locality controller fails to update pod test

---

pkg/app/grpcurl.go
pkg/tests/tasks/traffic/ingress/grpc_https_gateway_test.go

- removed debug resource which was added accidentally a long time ago
Test results:
- TestExposeGrpcWitPassthroughGateway https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/maistra/job/maistra-test-tool/3074/
- TestExposeGrpcWithHttpsGateway https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/maistra/job/maistra-test-tool/3075/

Wait till GrpCurl job is ready

---

pkg/tests/non-dependant/bug_multiple_smcp_test.go
pkg/tests/non-dependant/olm_webhooks_test.go
pkg/tests/ossm/bug_istiopods_test.go
pkg/tests/ossm/bug_rolebinding_test.go
pkg/tests/ossm/discovery_selectors_test.go
pkg/tests/ossm/ior_test.go
pkg/tests/ossm/prometheus_scoped_scraping_test.go
pkg/tests/ossm/route_prevent_additional_ingress_test.go
pkg/tests/tasks/injection/native_sidecars_test.go
pkg/tests/tasks/injection/tproxy_test.go
pkg/tests/tasks/observability/federated_openshift_monitoring_test.go
pkg/tests/tasks/observability/openshift_monitoring_test.go
pkg/tests/tasks/security/authentication/mtls_migration_test.go
pkg/tests/tasks/security/authorization/deny_test.go
pkg/tests/tasks/security/authorization/ext_auth_test.go
pkg/tests/tasks/security/authorization/http_test.go
pkg/tests/tasks/security/authorization/trust_domain_test.go
pkg/tests/tasks/security/certificate/external_ca_test.go
pkg/tests/tasks/traffic/egress/access_external_services_test.go
pkg/tests/tasks/traffic/fault_injection_test.go
pkg/tests/tasks/traffic/ingress/gatewayapi_test.go
pkg/tests/tasks/traffic/ingress/ingress_gateways_test.go
pkg/tests/tasks/traffic/request_routing_test.go
pkg/tests/tasks/traffic/request_timeouts_test.go
pkg/tests/tasks/traffic/traffic_mirroring_test.go
pkg/tests/tasks/traffic/traffic_shifting_test.go

- Add Disconnected label on passed tests
- Clean-up
- stabilize flaky tests
- investigate failed tests and the possibility of the next expansion (need to expand mirroring)
Related:
- MTT - [3120](https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/maistra/job/maistra-test-tool/3120/console)
- [OSSM-1514](https://issues.redhat.com/browse/OSSM-1514)

OSSM-1514: Expand Disconnected test cases

---

images.yaml

+ aligned fortio/httpbin images across all platforms
**Verification on x86 clusters:**
2.4 https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/maistra/job/maistra-test-tool/3113/
2.5 https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/maistra/job/maistra-test-tool/3114/
2.6 https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/maistra/job/maistra-test-tool/3111/
`TestEnvoyExtAuthzRequestPayloadTooLarge` passed after bump `extauthz` image to `1.22`  https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/maistra/job/maistra-test-tool/3119/console
**Verification on arm cluster:**
IOR flakiness only (will be fixed in the [different pr](https://github.com/maistra/maistra-test-tool/pull/767)) …

Do not use the latest tag for image which we do not control

---

pkg/tests/ossm/setup.go
pkg/tests/tasks/migration/bookinfo-gateway.yaml
pkg/tests/tasks/migration/main_test.go
pkg/tests/tasks/migration/migration_test.go
pkg/util/curl/curl.go
pkg/util/env/env.go
pkg/util/oc/pod_commands.go
pkg/util/test/test.go

Adds a test that:
1. Creates a 2.6 and 3.0 controlplane.
2. Deploys bookinfo + bookinfo gateway.
3. Migrates bookinfo from 2.6 --> 3.0 controlplane.
4. Ensures that requests to bookinfo through the gateway succeed before and after migration.
Subsequent tests should make common methods for things like creating and cleaning up `Istio` and `IstioCNI` resource.
This test also requires that your cluster can provision `LoadBalancer` services.

Add a test for 2.6 --> 3.0 migration

---

pkg/tests/non-dependant/bug_multiple_smcp_test.go
pkg/tests/ossm/bug_istiopods_test.go
pkg/tests/ossm/deploy_on_infra_test.go
pkg/tests/ossm/ior_test.go
pkg/tests/ossm/ratelimit_test.go
pkg/tests/ossm/route_prevent_additional_ingress_test.go
pkg/tests/ossm/setup.go
pkg/tests/ossm/smoke_test.go
pkg/tests/ossm/yaml/smcp.yaml
pkg/tests/tasks/migration/cert_manager_test.go
pkg/tests/tasks/migration/migration_test.go
pkg/tests/tasks/traffic/egress/egress_gateways_test.go
pkg/tests/tasks/traffic/egress/egress_gateways_tls_file_mount_test.go
pkg/tests/tasks/traffic/egress/egress_gateways_tls_sds_test.go
pkg/tests/tasks/traffic/egress/egress_wildcard_hosts_test.go
pkg/tests/tasks/traffic/egress/yaml_vars.go

- Do not use Jaeger tracing when SMCP is 2.5 but OCP version is 4.19+
- Cleaned up unnecessary DefaultSMCP calls
- Return SMCP values from `DeployControlPlane` method (so in the test, we don't need to call Default SMCP again, we will have available the same SMCP values as were applied for deployment)

[OSSM-9386] Do not select Jaeger tracing on OCP 4.19+

---

Dockerfile

Replace @latest with 1.12.2
latest version 1.12.3 leads to:
```
STEP 11/13: RUN go install gotest.tools/gotestsum@latest     && go mod download
go: downloading gotest.tools/gotestsum v1.12.3
go: downloading gotest.tools v2.2.0+incompatible
go: gotest.tools/gotestsum@latest (in gotest.tools/gotestsum@v1.12.3): go.mod:3: invalid go version '1.23.0': must match format 1.23
Error: building at STEP "RUN go install gotest.tools/gotestsum@latest     && go mod download": while running runtime: exit status 1
make: *** [Makefile:44: image] Error 1
```
During `make image` operation

Pin gotestsum to v1.12.2

---

.github/workflows/main.yml

Avoid error: 
```
This is a scheduled Ubuntu 20.04 retirement. Ubuntu 20.04 LTS runner will be removed on 2025-04-15. For more details, see https://github.com/actions/runner-images/issues/11101
```
Details: 
https://github.com/actions/runner-images/issues/11101

Bump GitHub actions runner
