maistra/maistra-test-tool

- README.md
- tests/maistra/constants.go
- tests/maistra/tc_05_traffic_shifting_test.go
- tests/maistra/tc_06_tcp_traffic_shifting_test.go
- tests/maistra/tc_09_gateways_https_test.go
- tests/maistra/testdata/tcp-echo/tcp-echo-20-v2.yaml
- tests/maistra/testdata/tcp-echo/tcp-echo-all-v1.yaml
- tests/maistra/testdata/tcp-echo/tcp-echo-services.yaml
- tests/maistra/utils_common.go
- tests/maistra/utils_ocp.go
- Refactor code
- Add new release 1.1 sample tcp-echo yaml files in testdata
- Add tc 06 TCP traffic shifting
> Add tc 06 TCP traffic shifting

- README.md
- tests/maistra/constants.go
- tests/maistra/deploy_samples.go
- tests/maistra/tc_03_request_routing_test.go
- tests/maistra/tc_04_fault_injection_test.go
- tests/maistra/tc_05_traffic_shifting_test.go
- tests/maistra/tc_06_tcp_traffic_shifting_test.go
- tests/maistra/tc_07_request_timeouts_test.go
- tests/maistra/tc_08_control_ingress_test.go
- tests/maistra/tc_09_gateways_https_test.go
- tests/maistra/tc_10_egress_traffic_test.go
- tests/maistra/tc_11_egress_tcp_traffic_test.go
- tests/maistra/tc_12_circuit_breaking_test.go
- tests/maistra/tc_13_mirroring_test.go
- tests/maistra/testdata/bookinfo/platform/kube/bookinfo.yaml
- tests/maistra/utils_common.go
- tests/maistra/utils_ocp.go
- Refactor code. Now certain test cases cover the bookinfo sample deployment and cleanup automatically
- Add mirroring test case
> Refactor code and Add tc 13 mirroring test case

- install/Pipfile.lock
- report/polarion/Pipfile.lock
- test/maistra/tc_08_control_ingress_test.go
- test/maistra/tc_09_gateways_https_test.go
Update Pipfile.lock urllib3 version to fix security alerts 
Update test scripts with IOR enabled
>  Update Pipfile.lock urllib3 version to fix security alerts 

- .gitignore
- README.md
- install/bookinfo.yaml
- install/istio/operator.py
- install/main.py
- install/member-roll.yaml
- install/ocp/ocp.py
- install/puller.py
- install/user-creation.sh
- test/maistra/bookinfo_install.sh
- test/maistra/util/kube_utils.go
Refactor hardcoded cluster-admin user.
- Now, registry-puller and operators are installed by cluster-admin user.
- ContorlPlane and other configurations are applied by regular user.
Refactor hardcoded namespace of ControlPlane.
Reduce number of environment variables
Refactor installation smoke test
> Update installation scripts for multitenancy features

- install/istio/operator.py
- install/main.py
- install/member-roll.yaml
- scripts/setup_jenkins_worker.sh
- test/maistra/tc_16_mtls_https_test.go
- test/maistra/tc_18_authorization_tcp_test.go
Fixing several issues in installation scripts
Fixing two test cases cleanup issues
> Fixing issues

- install/main.py
- install/user-creation.sh
- adds new users to the cluster
- makes pwds configurable through env variables
> feat: adds new test users

- .gitignore
- install/es_operator.yaml
- install/istio/operator.py
- install/kiali_operator.yaml
- install/main.py
- install/ocp/ocp.py
- Replace old oc client with latest OpenShift 4 oc client 
- Add Elasticsearch Operator and update kiali operator installation
> Installation Updates

- tests/samples_extend.go
Depends on https://github.com/maistra/istio-operator/pull/601
> MAISTRA-1937 Move ServiceMeshExtension into maistra.io apiGroup

- tests/config/smcp-invalid-fields/smcp.yaml
- tests/samples.go
- tests/smcp_invalid_fields_test.go
- tests/test_cases.go
- tests/util/ocp_utils.go
Adding a test case to cover the MAISTRA-1983 SMCP installation.
> [MAISTRA-1985] Adding a QE Coverage for MAISTRA-1983

- tests/samples_extend.go
- tests/task_traffic_egress_wildcards.go
- tests/test_cases.go
Hi 
@yxun 
Submitting the https://istio.io/latest/docs/tasks/traffic-management/egress/wildcard-egress-hosts/ test case
Feel free to make any required changes.
Best Regards,
Guilherme Baufaker Rêgo
> Adding Egress Wildcards Test case

- tests/samples_extend.go
- tests/task_traffic_egress_wildcards.go
Adding Egress with Single Hosting Server
Original Reference: https://istio.io/latest/docs/tasks/traffic-management/egress/wildcard-egress-hosts/#wildcard-configuration-for-a-single-hosting-server
> Adding Test for Egress Wildcard with Single Host Server

- tests/task_policies_enable_rate_limits_test.go
@gbaufake can u please help to merge the PR
> Fixed the flaky test

- tests/samples_extend.go
- tests/task_traffic_egress_accessing_external_services_test.go
PSI: Replace external services test site from google.com to redhat.com
> PSI: Replace external services test site from google.com to redhat.com

- tests/task_traffic_egress_accessing_external_services_test.go
> Egress test: Fix kubectl replace configmap delay

- tests/smcp_recursive_lock_test.go
- tests/test_cases.go
Test Run on the fixed version:
```
go test -run 31 -timeout 1m -v
Preparing environment configurations. Wait to start...
=== RUN   31
2021-04-09T17:59:42.423043Z     info    Running command oc rsh -c discovery $(oc get pods -l app=pilot --no-headers | awk '{print $1}') curl -v http://localhost:8080/debug/cdsz
2021-04-09T17:59:46.214553Z     info    Command output: 
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET /debug/cdsz HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.61.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< …
```
> Adding Automation to MAISTRA-2150

- tests/config/goldPanda/resource.yaml
- tests/samples.go
- tests/smcp_path_normalization_test.go
- tests/task_policies_control_headers_routing_test.go
- tests/test_cases.go
Automation for CVE fixes on 2.0.4
> Automation for MAISTRA-2354

- pkg/ossm/sme_install.go
> WASM: Print proxy log upon exit

- Jenkinsfile
This allows to use predefined credentials for e.g. standard automation user without passing username/password explicitly.
> Adding option to use jenkins credentials instead of user/password params

- Jenkinsfile
Removing a code which was preventing that
> We need to be able to build this job from a parent job

- pkg/ossm/smoketest.go
Added a test to check if istiod pod is running and print istiod logs
> added a test to check istiod logs

- pkg/ossm/smoketest.go
Added sample test for checking bookinfo product page url
> added bookinfo product page url test

- testdata/examples/x86/federation/install.sh
- testdata/examples/x86/federation/install_diff_cert.sh
PR created for https://issues.redhat.com/browse/OSSM-1108
> Rosa federation

- pkg/tasks/traffic/egress/egress_tls_origination.go
- pkg/tasks/traffic/egress/yaml_configs.go
Signed-off-by: Yuanlin Xu <yuanlin.xu@redhat.com>
> Istio 1.6.x egress tls origination ALPN patch

- Jenkinsfile
> [maistra-2.1] OSSM-1508: enable build discarder so the disk usage does not grow

- Jenkinsfile
> [development] OSSM-1508: enable build discarder so the disk usage does not grow

- Jenkinsfile
> [maistra-2.2] OSSM-1508: enable build discarder so the disk usage does not grow

- Jenkinsfile
> [maistra-1.1] OSSM-1508: enable build discarder so the disk usage does not grow

- Jenkinsfile
> [maistra-2.0-p] OSSM-1508: enable build discarder so the disk usage does not grow

- Jenkinsfile
> [maistra-2.0-z] OSSM-1508: enable build discarder so the disk usage does not grow

- testdata/examples/federation/export/smcp.yaml
- testdata/examples/federation/import/smcp.yaml
Updated the Federation Control Plane Updated
> Fedration_cp_verision

- pkg/ossm/smcp_install.go
- pkg/ossm/smcp_tls_ssl.go
- pkg/tasks/traffic/egress/egress_gateways_tls_file_mount.go
- scripts/auth/authorization.sh
- testdata/examples/failover/setup.sh
- testdata/examples/federation/install.sh
- testdata/examples/federation/install_diff_cert.sh
Signed-off-by: Yuanlin <yuanlin.xu@redhat.com>
This change is related to https://issues.redhat.com/browse/OSSM-1718
We need to check a SMCP condition instead of a SMMR condition in OSSM 2.2.2+
> Update oc wait commands in test scripts

- Jenkinsfile
- pkg/ossm/smcp_install.go
- pkg/ossm/yaml_configs.go
- templates/smcp-templates/v2.3/cr_2.3_default_template.yaml
Adding config to install SMCP version 2.3
> SMCP install config for 2.3

- .gitleaks.toml
Signed-off-by: Yuanlin <yuanlin.xu@redhat.com>
> Update gitleaks toml

- pkg/federation/fed_single_cluster_install.go
Signed-off-by: Yuanlin <yuanlin.xu@redhat.com>
> Increase sleep time in T31 for jenkins builds

- Jenkinsfile
> Adding email notification

- Dockerfile
- Jenkinsfile
- tests/main_test.go
- tests/test.env
- tests/test_cases.go
We need to run just a sub set of tests for interop testing. This is quick attempt to achieve that.
> Adding test groups

- pkg/ossm/bug_istiopods.go
- pkg/util/kube.go
- scripts/smmr/clean_members_50.sh
- scripts/smmr/create_members_50.sh
- tests/test_cases.go
Adding test case to test istio pod stuck on restarts:
https://issues.redhat.com/browse/OSSM-2434
> Add new test case for ossm-2434

- pkg/ossm/bug_istiopods.go
- pkg/util/kube.go
- scripts/smmr/clean_members_50.sh
- scripts/smmr/create_members_50.sh
- tests/test_cases.go
Adding a new test case for maistra tool on maistra-2.3 regarding: 
https://issues.redhat.com/browse/OSSM-2434
> Adding new test case for: OSSM-2434

- pkg/ossm/smcp_annotation.go
- pkg/util/kube.go
Adding improvement to T29 test case to avoid flaky results when the pod is not ready to get the annotations:
https://issues.redhat.com/browse/OSSM-3031
> Improve over T29 test case

- pkg/ossm/smcp_annotation.go
- pkg/util/kube.go
Improve T29 test case: https://issues.redhat.com/browse/OSSM-3031
> Improve T29 test case

- pkg/ossm/bug_multiple_smcp.go
- pkg/ossm/yaml_configs.go
- tests/test_cases.go
Creating the Multiple Control Planes in the namespace.
Validating the Pods, working with the expected results.
> multiple_smcp_validation

- testdata/examples/x86/bookinfo/bookinfo-db.yaml
- testdata/examples/x86/bookinfo/bookinfo-ratings-v2.yaml
- testdata/examples/x86/bookinfo/bookinfo.yaml
This should solve the problem on IPv6
> Updating bookinfo images tags to 2.3.0

- testdata/examples/x86/httpbin/httpbin.yaml
- testdata/examples/x86/httpbin/httpbin_legacy.yaml
- testdata/examples/x86/httpbin/httpbinv1.yaml
- testdata/examples/x86/httpbin/httpbinv2.yaml
Adding support for ipv6 on httpbin
> Adding httpbin support for ipv6

- pkg/tasks/security/authorization/externalauthorization.go
- pkg/tasks/security/authorization/yaml_configs.go
- pkg/util/kube.go
- tests/test_cases.go
https://istio.io/latest/docs/tasks/security/authorization/authz-custom/
Executed the Manual steps and added the automation test case for Maistra-test-tool.
> Automation for External Authorization 

- pkg/ossm/operator.go
- pkg/util/kube.go
- tests/test_cases.go
Adding a new test case regarding  OSSM-3515. For more information regarding test steps: https://issues.redhat.com/browse/OSSM-3515
> Adding new test case regarding OSSM-3515

- pkg/ossm/bug_istiopods.go
- pkg/util/kube.go
Adding fix to T35 test case that was not in this branch: https://issues.redhat.com/browse/OSSM-3564
> Add fix to T35

- pkg/ossm/operator.go
Adding subtest case related to this task: https://issues.redhat.com/browse/OSSM-459
Should be tracked on this task: https://issues.redhat.com/browse/OSSM-3516
> Adding new subtest case to T40

- pkg/ossm/bug_smm_delete_smmr.go
- pkg/ossm/yaml_configs.go
- pkg/util/kube.go
- tests/test_cases.go
The Bug of OSSM-2374 is fixed in 2.3.2
We can Merge, Now
2.3.2 is already in Production.
@monroe-dylan-m: It is already reviewed by Fransisco and Dylan. 
Due to some branch Conflict, this https://github.com/maistra/maistra-test-tool/pull/376  PR is deleted
> Maistra Test case for bug OSSM-2374

- pkg/ossm/yaml_configs.go
> fix T39 flaky test

- pkg/tests/ossm/smoke_test.go
- pkg/util/oc/oc.go
> OSSM-3639 Refactor TestBookinfo (A2)

- pkg/tests/tasks/traffic/ingress/ingress_without_tls_termination_test.go
- pkg/tests/tasks/traffic/ingress/secure_gateways_test.go
- pkg/tests/tasks/traffic/ingress/yaml_vars.go
- pkg/util/istio/istio.go
This PR includes:
- Refactor  TestIngressWithoutTlsTermination (T10)
- Add an util method GetIngressGatewaySecurePort in pkg/util/istio/
> OSSM-3767 Refactor TestIngressWithoutTlsTermination (T10)

- pkg/tests/ossm/deploy_on_infra_test.go
- pkg/util/oc/pod_commands.go
Currently, it doesn't retry and only waits 30s. It has failed on some test runs.
> Fix WaitPodReady()

- pkg/tests/ossm/deploy_on_infra_test.go
Jira: https://issues.redhat.com/browse/OSSM-3837
> OSSM-3837: skip T40 test case until is fixed

- pkg/tests/ossm/smcp_must_gather_test.go
- pkg/util/env/env.go
- pkg/util/test/subtest.go
- pkg/util/test/test.go
- pkg/util/test/test_helper.go
- scripts/runtests.sh
This commit also moves the result output files to ./tests/result-<timestamp>
> Run must-gather on each test failure

- scripts/runtests.sh
Jira: https://issues.redhat.com/browse/OSSM-3483
To improve the output I added a new func to write a small txt that parses the output.log file and will result in a document with this format for different purposes:
```
TEST CASE NAME: TestSMCPInstall/install
STEP: 1: Delete and re-create Namespace 
STEP: 2: Create SMCP v2.3 and verify it becomes ready 
STEP: 3: Install SMCP 
STEP: 4: Check SMCP is Ready 
STEP: 5: Delete SMCP and verify if this deletes all resources 
STEP: 6: Delete SMCP in namespace istio-system 
TEST CASE NAME: TestSMCPInstall/upgrade_v2.2_to_v2.3
STEP: 1: Delete and re-create Namespace 
STEP: 2: Create SMCP v2.2 and verify it becomes ready 
STEP: 3: Install SMCP 
STEP: 4: Check SMCP is Ready 
STEP: 5: Upgrade SMCP from v2.2 to v2.3 
STEP: 6: Install SMCP 
STEP: 7: Check …
```
> OSSM-3483 Adding documentation script

- images.yaml
- pkg/tests/tasks/security/authorization/ext_auth_test.go
Added the ext-auth image to IBM P platform
> OSSM-3928: Added the ext-auth image for IBM P platfrom

- pkg/tests/tasks/observability/openshift_monitoring_test.go
Jira: https://issues.redhat.com/browse/OSSM-3958
Fix error in trim to make the test case works properly
> OSSM-3958 fix test case TestOpenShiftMonitoring

- pkg/tests/ossm/smoke_test.go
Added a new function to validate that routes are created in smcp deploy
Added this validation to add coverage and regression for this bug: https://issues.redhat.com/browse/OSSM-4069
> OSSM-4072: validate routes created in SMCP installation

- pkg/tests/tasks/security/authorization/ext_auth_test.go
Adding testing for tech preview for ext-authz-grpc for this [Jira ](https://issues.redhat.com/browse/OSSM-3979?focusedId=22464390&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-22464390)
> OSSM-3979 E2E test for ext-authz-grpc

- pkg/tests/ossm/deploy_on_infra_test.go
Jira: https://issues.redhat.com/browse/OSSM-3837
After the last changes on this test case, the cleanup was not correctly cleaning the patch over the subscription, this is fixed now and I added some improvements to the test case to avoid some flaky results:
- Fix clean up of the subscription deleting now the entire `/spec/config`
- Adding a wait pod ready for the cleanup because we need to ensure that after the revert of the change the pod is ready again to not impact another test case execution. TODO: after we merge this PR https://github.com/maistra/maistra-test-tool/pull/597 we need to port a func called waitOperatorSucceded to be able to use globally and use in this test case to ensure the operator is Ok before continuing in the rest of the test cases
- Increase the retry time in …
> OSSM-3837 TestDeployOnInfraNodes, fix patch and adding improvement to the test

- Dockerfile
Jira: https://issues.redhat.com/browse/OSSM-4367
Adding git to the container to avoid failures in some of the test cases
> OSSM-4367 adding git to DockerFile

- pkg/tests/tasks/security/authorization/tcp_test.go
Jira: https://issues.redhat.com/browse/OSSM-4380
> OSSM-4380 TestAuthorizationTCPTraffic  increase attempts for assertPortTcpEchoAccepted(t, ns, podIP, "9002")

- pkg/certmanageroperator/install.go
Jira: https://issues.redhat.com/browse/OSSM-4622
To avoid flakiness in cert-manager test cases I improved the certManagerOperatorExists func, now will look for the csv using as filter the replaces version, the test case was failing because we were looking for the base version and now it's updated
> OSSM-4622 Fix verification for certManagerOperatorExists and increase retries

- README.md
- pkg/tests/ossm/smcp_annotation_test.go
- pkg/tests/ossm/smcp_must_gather_test.go
- scripts/runtests.sh
Jira: https://issues.redhat.com/browse/OSSM-4500
Make some changes to the run.sh script to change the host of the images when disconnected testing group is selected
> OSSM-4500 Allow execute disconnected testing group

- pkg/tests/ossm/prometheus_scoped_scraping_test.go
> TestOperatorCanUpdatePrometheusConfigMap

- Makefile
Jira: https://issues.redhat.com/browse/OSSM-4671
The idea of this PR is to improve the information that we can easily show for users of the tool:
- Show which are the available testing groups
- Show test package for each testing group
- Show Help to know which are the available commands in the make file
> OSSM-4671 Improve make information

- README.md
Update read me information with the information to use new make options
> Updating read me information

- pkg/tests/tasks/security/authorization/ext_auth_test.go
Updating the GRPC tech-preview to GA.
We can Merge this test case, before 2.4.3 testing.
> Updating the GRPC SM yaml

- images.yaml
Updated all the ARM new images for the 2.4.3
> arm_bookinfo_images

- images.yaml
Updated the X86 image tag with the 2.4.0
> Updating the x86 bookinfo images

- pkg/tests/ossm/route_prevent_additional_ingress_test.go
https://issues.redhat.com/browse/OSSM-5026
> MTT: Prevent the route for Additional Ingress

- pkg/tests/tasks/security/authorization/ext_auth_test.go
https://issues.redhat.com/browse/OSSM-4975, 
Added the Extra Parameters:
headersToDownstreamOnAllow
headersToDownstreamOnDeny
headersToUpstreamOnAllow
> MTT: Added the extra parameters to the HTTP Extension Authorization Policy

- pkg/tests/tasks/extensions/threescale_wasm_plugin_test.go
`APPLY_WASM_PLUGINS_TO_INBOUND_ONLY` is no longer supported in v2.5, so we have to adjust our tests for 3scale plugin.
> OSSM-5445: Adjust TestThreeScaleWasmPlugin to v2.5

- pkg/certmanageroperator/install.go
--- PASS: TestPluginCaCert 
Tested locally with the updated version of the cert-manager-operator version 
Maistra test tool run - SUCCESS
- Job URL: https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/maistra/job/maistra-test-tool//1119
> update the cert-manager-operator version

- .gitignore
- pkg/certmanageroperator/install.go
- pkg/tests/ossm/deploy_on_infra_test.go
- pkg/tests/tasks/security/certmanager/istio_csr_test.go
- pkg/util/operator/operators.go
ref: https://issues.redhat.com/browse/OSSM-5683
> [OSSM-5683] Improve waiting for CSV is ready

- pkg/tests/tasks/traffic/ingress/gatewayapi_test.go
- pkg/util/gatewayapi/gatewayapi.go
ref: https://issues.redhat.com/browse/OSSM-5574
also fix for: https://issues.redhat.com/browse/OSSM-5550
> [OSSM-5574] Update GatewayAPI version for OSSM2.5

- pkg/tests/ossm/deploy_on_infra_test.go
ref: https://issues.redhat.com/browse/OSSM-5713
> [OSSM-5713] Add test for maistra.io/exclude-cni label

- pkg/tests/ossm/operator/clusterwide_mode_test.go
- pkg/util/oc/pod_commands.go
Issue: https://issues.redhat.com/browse/OSSM-4847
> OSSM-4847: Increase test coverage over Cluster Wide test case

- images.yaml
- pkg/tests/ossm/smm_test.go
- pkg/tests/tasks/security/authorization/ext_auth_test.go
- pkg/tests/tasks/security/authorization/tcp_test.go
- pkg/tests/tasks/traffic/circuit_breaking_test.go
- pkg/tests/tasks/traffic/ingress/secure_gateways_test.go
- pkg/tests/tasks/traffic/traffic_tcp_shifting_test.go
Added the hello-world image for the ARM cluster.
> OSSM-5846: Updated  image to install the applications on the ARM

- pkg/tests/ossm/smcp_annotation_test.go
Tested with the ARM cluster, it works as expected.
> update arm group for TestSMCPAnnotations

- pkg/tests/ossm/ior_test.go
for the 2.5 the IOR the default is false
> update the ior and skip arm

- pkg/tests/ossm/route_prevent_additional_ingress_test.go
Creating the additional route for the Ingress gateway.
> OSSM-4453: igw route

- pkg/tests/tasks/security/certmanager/plugin_ca_test.go
There was a change in the log message in Istio 1.20
https://github.com/istio/istio/pull/47769/files#diff-36e3ba60ba5256197af5bb265d7498cefbe34323cc4cb9363eae83ee3f76422fR143
> [OSSM-6747] Update log message in OSSM 2.6 for TestPluginCaCert test

- pkg/tests/non-dependant/bug_multiple_smcp_test.go
- pkg/tests/non-dependant/olm_webhooks_test.go
- pkg/tests/ossm/smcp_must_gather_test.go
- pkg/util/oc/oc.go
- pkg/util/oc/oc_struct.go
Fix tests after changes in validation webhook, this commit https://github.com/maistra/istio-operator/commit/a33d372e098dc22319da45f7da4002cdba7252ee
- [OSSM-6799] Fix TestSMCPMultiple after changes in validatingwebhookconfiguration
- [OSSM-6800] Fix TestMustGather test after changes in validatingwebhookconfiguration
- [OSSM-6811] Create test case for OLM validationg/mutating webhooks
> Fix tests after changes in validation webhook

- images.yaml
Fixed the failed test cases and tested in them local, it worked as expected.
> OSSM-6820: updating the arm images

- images.yaml
- pkg/app/minio.go
- pkg/certmanageroperator/install.go
- pkg/certmanageroperator/yaml/cert-manager-operator.yaml
- pkg/tempo/install.go
- pkg/tempo/yaml/open-telemetry-operator.yaml
- pkg/tempo/yaml/tempo-operator.yaml
- pkg/tempo/yaml/tempoStack.yaml
- pkg/tests/ossm/deploy_on_infra_test.go
- pkg/tests/ossm/tempo_tracing_test.go
- pkg/tests/tasks/observability/custom_prometheus_test.go
- pkg/util/oc/oc.go
- pkg/util/oc/oc_struct.go
- pkg/util/operator/operators.go
* Added test for Tempo
* Added Minio app and Tempo/Otel installation via OLM
* Installation via OLM was generalized and simplified (affects also certmanageroperator)
> [OSSM-6734] Test coverage for Tempo/Otel integration

- images.yaml
Verified on IBM P an Z cluster :ok:
> Update bookinfo IBM images

- pkg/tests/ossm/ior_test.go
Related:
- MTT task [OSSM-6943](https://issues.redhat.com/browse/OSSM-6943)
- Bug [OSSM-6615](https://issues.redhat.com/browse/OSSM-6615)
Due to the flaky nature of  the error need to repeat check section few times (5)
SMCP 2.4 skipped as issue was not fixed in it
Example of fail (smcp 2.4):
```
ior_test.go:283: STEP 4: Try to delete istiod pod and check the bookinfo route few times (5)
ior_test.go:285:    SUCCESS: 0: Headless service in istio namespace did not broke IOR
ior_test.go:285:    SUCCESS: 1: Headless service in istio namespace did not broke IOR
ior_test.go:285:    FAILURE: 2: Headless service in istio namespace broke IOR; expected to find the string 'istio-ingressgateway' in the output, but it wasn't found; full output:
pod "istiod-basic-6d56bb8d8d-g7lfh" deleted
Waiting for …
```
> OSSM-6943: Add test IOR with headless service

- pkg/tests/ossm/bug_istiopods_test.go
- pkg/tests/ossm/discovery_selectors_test.go
- pkg/tests/ossm/setup.go
- pkg/tests/ossm/tempo_tracing_test.go
- pkg/util/oc/oc.go
- pkg/util/oc/oc_struct.go
a run with all tests passed https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/maistra/job/maistra-test-tool/2513/
> Remove oc replace

- Dockerfile
upgrade is waiting for an input
```
Transaction Summary:
Installing: 0 packages
Reinstalling: 0 packages
Upgrading: 3 packages
Obsoleting: 0 packages
Removing: 0 packages
Downgrading: 0 packages
Is this ok [y/N]: 
```
> Fix stuck build in openshift-ci

- pkg/tests/ossm/ior_test.go
Close-loop
Related:
- [OSSM-6295](https://issues.redhat.com/browse/OSSM-6295)
- [OSSM-6975](https://issues.redhat.com/browse/OSSM-6975)
- [mtt-2518](https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/maistra/job/maistra-test-tool/2518)
Sum-up:
- argocd.argoproj.io* label :green_circle: 
- argocd.argoproj.io* annotation :green_circle: 
- argocd.argoproj.io/instance label :red_circle: 
- argocd.argoproj.io/instance annotation :green_circle: 
Example of fail with 2.5.1 operator: 
```
=== RUN   TestIOR/Check_argocd.argoproj.io_labels_from_Gateways_to_Routes_except_argocd.argoproj.io/instance
ior_test.go:257: Reference: https://issues.redhat.com/browse/OSSM-6295
ior_test.go:263:    
ior_test.go:263: STEP 1: Ensure the IOR enabled
ior_test.go:266:    
ior_test.go:266: …
```
> OSSM-6975: Add test IOR copies argocd.argoproj.io except instance label

- pkg/tests/ossm/operator/addons_disable_test.go
ref. : https://issues.redhat.com/browse/OSSM-8258
https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/maistra/job/maistra-test-tool/3009/
> [OSSM-8258] Test for addons disable

- pkg/app/sleep.go
- pkg/tests/tasks/security/authorization/ext_auth_test.go
Related:
- Bug - [OSSM-5850](https://issues.redhat.com/browse/OSSM-5850)
- MTT run with GA operator - [3006](https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/maistra/job/maistra-test-tool/3006/console) 
- MTT run with 2.4 SMCP of 2.4.5 operator - [3007](https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/maistra/job/maistra-test-tool/3007/console) 
- Full MTT run with GA operator as few changes related to the sleep app were done - [3011](https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/maistra/job/maistra-test-tool/3011/console)
>  OSSM-8251: Add test for file upload case

- pkg/tests/ossm/smcp_secret_test.go
Test already existed:
- Added reference
- Cleaned up a bit
Reference:
- [OSSM-1094](https://issues.redhat.com/browse/OSSM-1094)
- Jenkins MTT:  [3071](https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/maistra/job/maistra-test-tool/3071)
> OSSM-8253: Update and add reference to test T52

- pkg/tests/ossm/ior_test.go
- Move gateway deletion before IOR is disabled
- Wait for SMCP is ready after IOR is enabled/disabled
- Delete leftover routes after IOR is disabled which can happen sometimes
MTT on arm: https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/maistra/job/maistra-test-tool/3138/ 
MTT on x86:  https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/maistra/job/maistra-test-tool/3143/
> Stability improvements for IOR tests

- pkg/tests/ossm/initcontainer_test.go
MTT: https://master-jenkins-csb-servicemesh.apps.ocp-c1.prod.psi.redhat.com/job/maistra/job/maistra-test-tool/3144/
> Fix hardcoded sleep image

- pkg/tests/ossm/setup.go
- pkg/tests/tasks/migration/enable-strict-mtls-peer-auth.yaml
- pkg/tests/tasks/migration/main_test.go
- pkg/tests/tasks/migration/migration_test.go
- pkg/util/check/assert/http_response.go
- pkg/util/env/env.go
- pkg/util/oc/oc.go
- pkg/util/oc/oc_struct.go
- pkg/util/oc/pod_commands.go
Adds external LB test to migration suite.
> Add external lb
